import { z } from 'zod';

/**
 * Branded identifier types, inferred from their Zod schemas (AGENTS.md section
 * 7.2).
 *
 * Persisted IDs are UUIDs generated by application code (section 5.3), never by
 * an LLM. Branding keeps a `ClaimId` from being passed where a `SpanId` is
 * expected, which matters once the graph has nine entity types that all look
 * like strings at runtime.
 *
 * LLM stages instead work with short **local IDs** (`s12`, `c3`, `i2`). The
 * pipeline maps local IDs to UUIDs when persisting; the two never mix within one
 * structure, which is why `LocalId` is branded too.
 */

export const documentIdSchema = z.uuid().brand<'DocumentId'>();
export const spanIdSchema = z.uuid().brand<'SpanId'>();
export const runIdSchema = z.uuid().brand<'RunId'>();
export const runEventIdSchema = z.uuid().brand<'RunEventId'>();
export const revisionIdSchema = z.uuid().brand<'RevisionId'>();
export const claimIdSchema = z.uuid().brand<'ClaimId'>();
export const inferenceIdSchema = z.uuid().brand<'InferenceId'>();
export const relationIdSchema = z.uuid().brand<'RelationId'>();
export const findingIdSchema = z.uuid().brand<'FindingId'>();

export type DocumentId = z.infer<typeof documentIdSchema>;
export type SpanId = z.infer<typeof spanIdSchema>;
export type RunId = z.infer<typeof runIdSchema>;
export type RunEventId = z.infer<typeof runEventIdSchema>;
export type RevisionId = z.infer<typeof revisionIdSchema>;
export type ClaimId = z.infer<typeof claimIdSchema>;
export type InferenceId = z.infer<typeof inferenceIdSchema>;
export type RelationId = z.infer<typeof relationIdSchema>;
export type FindingId = z.infer<typeof findingIdSchema>;

/**
 * A short identifier assigned by a pipeline stage: one or more lowercase
 * letters followed by digits, e.g. `c3`, `s12`, `i2`.
 *
 * The prefix is a readability convention, not a type distinction — a draft
 * references claims and spans in different fields, so position already says
 * which kind is meant.
 */
export const localIdSchema = z
  .string()
  .regex(/^[a-z]+[0-9]+$/, 'a local ID looks like "c3" or "s12"')
  .brand<'LocalId'>();
export type LocalId = z.infer<typeof localIdSchema>;

/** Every persisted ID brand, for code that is generic over them. */
export type EntityId =
  | DocumentId
  | SpanId
  | RunId
  | RunEventId
  | RevisionId
  | ClaimId
  | InferenceId
  | RelationId
  | FindingId;

/**
 * Mints a fresh UUID for a branded ID type, e.g. `newId<ClaimId>()`.
 *
 * The caller chooses the brand, so `T` appears only in the return position.
 * That is deliberate for a mint function: there is no input to infer from.
 */
// eslint-disable-next-line @typescript-eslint/no-unnecessary-type-parameters
export function newId<T extends string>(): T {
  return crypto.randomUUID() as T;
}

/** Parses a string as a local ID, throwing if malformed. For stage code and fixtures. */
export function localId(value: string): LocalId {
  return localIdSchema.parse(value);
}
