/**
 * Branded identifier types.
 *
 * Persisted IDs are UUIDs generated by application code (AGENTS.md section 5.3),
 * never by an LLM. Branding keeps a `ClaimId` from being passed where a
 * `DocumentId` is expected, which matters once the graph has six entity types
 * that all look like strings at runtime.
 *
 * Phase 1 adds the remaining entity IDs and the `ArgumentGraph` schemas.
 */
declare const brand: unique symbol;

export type Branded<T, B extends string> = T & { readonly [brand]: B };

export type DocumentId = Branded<string, 'DocumentId'>;
export type SpanId = Branded<string, 'SpanId'>;
export type RunId = Branded<string, 'RunId'>;
export type RevisionId = Branded<string, 'RevisionId'>;
export type ClaimId = Branded<string, 'ClaimId'>;
export type InferenceId = Branded<string, 'InferenceId'>;
export type RelationId = Branded<string, 'RelationId'>;
export type FindingId = Branded<string, 'FindingId'>;

/**
 * Mints a fresh UUID for a branded ID type, e.g. `newId<ClaimId>()`.
 *
 * The caller chooses the brand, so `T` appears only in the return position.
 * That is deliberate for a mint function: there is no input to infer from.
 */
// eslint-disable-next-line @typescript-eslint/no-unnecessary-type-parameters
export function newId<T extends Branded<string, string>>(): T {
  return crypto.randomUUID() as T;
}
