import { sql } from 'drizzle-orm';
import type { AnyPgColumn } from 'drizzle-orm/pg-core';
import {
  boolean,
  check,
  doublePrecision,
  index,
  integer,
  jsonb,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core';
import {
  attribution,
  claimKind,
  documentRole,
  findingKind,
  inferenceScheme,
  modality,
  origin,
  pipelineStage,
  relationType,
  runEventType,
  runStatus,
  severity,
  spanFunction,
} from './enums.ts';

/**
 * Drizzle schema, mirroring `docs/argument-model.mermaid` (AGENTS.md section
 * 7.4).
 *
 * IDs are generated by application code (`newId<T>()`), not by the database, so
 * the pipeline can build a whole graph in memory and write it in one
 * transaction. The constraints an ER diagram cannot express — exactly-one
 * targets, confidence ranges, one thesis per revision — are CHECK constraints
 * and partial indexes here.
 */

export const documents = pgTable('document', {
  id: uuid('id').primaryKey(),
  sourceText: text('source_text').notNull(),
  title: text('title'),
  role: documentRole('role').notNull().default('other'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const spans = pgTable(
  'span',
  {
    id: uuid('id').primaryKey(),
    documentId: uuid('document_id')
      .notNull()
      .references(() => documents.id, { onDelete: 'cascade' }),
    ordinal: integer('ordinal').notNull(),
    charStart: integer('char_start').notNull(),
    charEnd: integer('char_end').notNull(),
    isHeading: boolean('is_heading').notNull().default(false),
    function: spanFunction('function').notNull().default('unclassified'),
    functionConfidence: doublePrecision('function_confidence'),
  },
  (t) => [
    index('span_document_idx').on(t.documentId),
    uniqueIndex('span_document_ordinal_idx').on(t.documentId, t.ordinal),
    check('span_offsets_ordered', sql`${t.charEnd} >= ${t.charStart}`),
    check(
      'span_confidence_range',
      sql`${t.functionConfidence} is null or (${t.functionConfidence} >= 0 and ${t.functionConfidence} <= 1)`,
    ),
  ],
);

export const revisions = pgTable(
  'revision',
  {
    id: uuid('id').primaryKey(),
    documentId: uuid('document_id')
      .notNull()
      .references(() => documents.id, { onDelete: 'cascade' }),
    // Self-referencing: editing (a later iteration) creates child revisions.
    // The explicit return type is required for a self-reference.
    parentRevisionId: uuid('parent_revision_id').references((): AnyPgColumn => revisions.id, {
      onDelete: 'set null',
    }),
    author: text('author').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('revision_document_idx').on(t.documentId),
    index('revision_parent_idx').on(t.parentRevisionId),
  ],
);

export const analysisRuns = pgTable(
  'analysis_run',
  {
    id: uuid('id').primaryKey(),
    documentId: uuid('document_id')
      .notNull()
      .references(() => documents.id, { onDelete: 'cascade' }),
    revisionId: uuid('revision_id').references(() => revisions.id, { onDelete: 'set null' }),
    status: runStatus('status').notNull().default('queued'),
    currentStage: pipelineStage('current_stage'),
    summary: text('summary'),
    modelConfig: jsonb('model_config'),
    error: text('error'),
    startedAt: timestamp('started_at', { withTimezone: true }),
    finishedAt: timestamp('finished_at', { withTimezone: true }),
  },
  (t) => [
    index('analysis_run_document_idx').on(t.documentId),
    index('analysis_run_revision_idx').on(t.revisionId),
    // A run that ended because the text is not an argument must say what it
    // appears to be instead (AGENTS.md section 6).
    check(
      'run_summary_when_not_an_argument',
      sql`${t.status} <> 'not_an_argument' or ${t.summary} is not null`,
    ),
  ],
);

export const runEvents = pgTable(
  'run_event',
  {
    id: uuid('id').primaryKey(),
    runId: uuid('run_id')
      .notNull()
      .references(() => analysisRuns.id, { onDelete: 'cascade' }),
    sequence: integer('sequence').notNull(),
    stage: pipelineStage('stage'),
    type: runEventType('type').notNull(),
    payload: jsonb('payload'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    // Monotonic per run: what lets the SSE stream resume from Last-Event-ID.
    uniqueIndex('run_event_run_sequence_idx').on(t.runId, t.sequence),
  ],
);

export const claims = pgTable(
  'claim',
  {
    id: uuid('id').primaryKey(),
    revisionId: uuid('revision_id')
      .notNull()
      .references(() => revisions.id, { onDelete: 'cascade' }),
    canonicalText: text('canonical_text').notNull(),
    kind: claimKind('kind').notNull(),
    modality: modality('modality').notNull().default('asserted'),
    origin: origin('origin').notNull(),
    attribution: attribution('attribution').notNull().default('author'),
    citation: text('citation'),
    confidence: doublePrecision('confidence').notNull().default(1),
    isThesis: boolean('is_thesis').notNull().default(false),
  },
  (t) => [
    index('claim_revision_idx').on(t.revisionId),
    // Exactly one thesis per revision (AGENTS.md section 6).
    uniqueIndex('claim_one_thesis_per_revision_idx')
      .on(t.revisionId)
      .where(sql`${t.isThesis}`),
    check('claim_confidence_range', sql`${t.confidence} >= 0 and ${t.confidence} <= 1`),
  ],
);

export const occurrences = pgTable(
  'occurrence',
  {
    claimId: uuid('claim_id')
      .notNull()
      .references(() => claims.id, { onDelete: 'cascade' }),
    spanId: uuid('span_id')
      .notNull()
      .references(() => spans.id, { onDelete: 'cascade' }),
    surfaceText: text('surface_text').notNull(),
  },
  (t) => [
    primaryKey({ columns: [t.claimId, t.spanId] }),
    index('occurrence_span_idx').on(t.spanId),
  ],
);

export const inferences = pgTable(
  'inference',
  {
    id: uuid('id').primaryKey(),
    revisionId: uuid('revision_id')
      .notNull()
      .references(() => revisions.id, { onDelete: 'cascade' }),
    conclusionClaimId: uuid('conclusion_claim_id')
      .notNull()
      .references(() => claims.id, { onDelete: 'cascade' }),
    scheme: inferenceScheme('scheme').notNull(),
    origin: origin('origin').notNull(),
    attribution: attribution('attribution').notNull().default('author'),
    formalization: jsonb('formalization'),
    confidence: doublePrecision('confidence').notNull().default(1),
  },
  (t) => [
    index('inference_revision_idx').on(t.revisionId),
    index('inference_conclusion_idx').on(t.conclusionClaimId),
    check('inference_confidence_range', sql`${t.confidence} >= 0 and ${t.confidence} <= 1`),
  ],
);

export const inferencePremises = pgTable(
  'inference_premise',
  {
    inferenceId: uuid('inference_id')
      .notNull()
      .references(() => inferences.id, { onDelete: 'cascade' }),
    claimId: uuid('claim_id')
      .notNull()
      .references(() => claims.id, { onDelete: 'cascade' }),
    origin: origin('origin').notNull(),
  },
  (t) => [
    // Composite key, so one claim cannot be listed twice in one step — which
    // would corrupt the joint-requirement count in support analysis.
    primaryKey({ columns: [t.inferenceId, t.claimId] }),
    index('inference_premise_claim_idx').on(t.claimId),
  ],
);

export const relations = pgTable(
  'relation',
  {
    id: uuid('id').primaryKey(),
    revisionId: uuid('revision_id')
      .notNull()
      .references(() => revisions.id, { onDelete: 'cascade' }),
    sourceClaimId: uuid('source_claim_id')
      .notNull()
      .references(() => claims.id, { onDelete: 'cascade' }),
    targetClaimId: uuid('target_claim_id').references(() => claims.id, { onDelete: 'cascade' }),
    targetInferenceId: uuid('target_inference_id').references(() => inferences.id, {
      onDelete: 'cascade',
    }),
    type: relationType('type').notNull(),
  },
  (t) => [
    index('relation_revision_idx').on(t.revisionId),
    index('relation_source_idx').on(t.sourceClaimId),
    index('relation_target_claim_idx').on(t.targetClaimId),
    index('relation_target_inference_idx').on(t.targetInferenceId),
    check(
      'relation_exactly_one_target',
      sql`(${t.targetClaimId} is null) <> (${t.targetInferenceId} is null)`,
    ),
  ],
);

export const findings = pgTable(
  'finding',
  {
    id: uuid('id').primaryKey(),
    revisionId: uuid('revision_id')
      .notNull()
      .references(() => revisions.id, { onDelete: 'cascade' }),
    kind: findingKind('kind').notNull(),
    severity: severity('severity').notNull(),
    explanation: text('explanation').notNull(),
    producedBy: text('produced_by').notNull(),
  },
  (t) => [index('finding_revision_idx').on(t.revisionId)],
);

export const findingTargets = pgTable(
  'finding_target',
  {
    findingId: uuid('finding_id')
      .notNull()
      .references(() => findings.id, { onDelete: 'cascade' }),
    claimId: uuid('claim_id').references(() => claims.id, { onDelete: 'cascade' }),
    inferenceId: uuid('inference_id').references(() => inferences.id, { onDelete: 'cascade' }),
    /** Stable order; for a circularity finding, the position round the cycle. */
    ordinal: integer('ordinal').notNull(),
  },
  (t) => [
    primaryKey({ columns: [t.findingId, t.ordinal] }),
    index('finding_target_claim_idx').on(t.claimId),
    index('finding_target_inference_idx').on(t.inferenceId),
    check('finding_target_exactly_one', sql`(${t.claimId} is null) <> (${t.inferenceId} is null)`),
  ],
);
